### ISSUE TITLE
mac_pkg to ansible-modules-extras

### ISSUE THREAD

**Issue by eyadsibai** [spencergibb/battleschool#27]
It would be nice if you could add mac_pkg to https://github.com/ansible/ansible-modules-extras/
in this way it can be used by others =)

**Comment by jschaul** [comment]
+1

**Comment by grootknol** [comment]
+1

**Comment by kerrmarin** [comment]
+1

**Comment by eyadsibai** [comment]
may be someone else should do it .... I see no reaction for many pull requests and many issues

**Comment by eyadsibai** [comment]
at least a comment from the author !!!

**Comment by spencergibb** [comment]
@eyadsibai sorry, haven't had much time to devote to battleschool. And this particular issue is asking for changes in someone else's project.

**Comment by eyadsibai** [comment]
@spencergibb thanks for the reply :)

**Comment by byrondover** [comment]
+1

Ansible is at the core battleschool. Please consider contributing back to the project.

**Comment by stackedsax** [comment]
@spencergibb mind if I submit a PR on your behalf to ansible?  I was thinking mac_pkg could go here:

https://github.com/ansible/ansible-modules-extras/tree/devel/packaging/os

**Comment by spencergibb** [comment]
I don't mind, it is after all [open source](https://github.com/spencergibb/battleschool/blob/master/LICENSE). I'm going to close this as it is does not involve changes to this project.

**Comment by edgarsj** [comment]
@stackedsax did you ever get around to work on the PR for ansible-modules-extras?

From what I've read in Ansible contribution guidelines, the main requirements are as follows:
1. GPLv3 license (@spencergibb are you ok to change the license accordingly?)
2. 2 commited mainteners (I could be one of them)
3. make it to conform to Ansible module standards
