### ISSUE TITLE
Update script install so battleschool can install homebrew

### ISSUE THREAD

**Issue by spencergibb** [spencergibb/battleschool#28]
https://groups.google.com/forum/#!topic/battle-school/4i-OGR04vD4

**Comment by enlewof** [comment]
This is still broken.  I think we should reopen this to get this fixed.

**Comment by spencergibb** [comment]
@enlewof I had forgotten to update https://github.com/spencergibb/ansible-osx/blob/master/homebrew.yml to use the new functionality, it is updated.  I just reinstalled homebrew with it.  If you have any more issues, please open a new issue.
