### ISSUE TITLE
Mac_pkg  is not a legal parameter?

### ISSUE THREAD

**Issue by robotsandcake** [spencergibb/battleschool#4]
Hello,

I wonder if you can help me, I'm not using battleschool but would really like to be able to use some of these playbooks for other purposes.  However whenever I tried to run any of the tasks involving installing applications, I get the following error:

`ERROR: mac_pkg is not a legal parameter in an Ansible task or handler`

Any idea what might be going on?

Thank you in advance :-)

**Comment by vladdancer** [comment]
For those who wants to run battle on El Capitan version it could be like this.
`battle --module-path=/usr/local/lib/python2.7/site-packages/usr/share/battleschool/library/`
