### ISSUE TITLE
Installation fails under El Capitan

### ISSUE THREAD

**Issue by kforsthoevel** [spencergibb/battleschool#46]
I can't install battleschool under Mac OS X 10.11 because of System Integrity Protection (SIP) see: https://support.apple.com/en-us/HT204899. You are no longer allowed to install into `/usr`.

```
running install_data
    creating /usr/share/battleschool
    error: could not create '/usr/share/battleschool': Operation not permitted
```

Could you please change the install directory to `/usr/local`.

Thanks.

**Comment by spencergibb** [comment]
closed via ae22fb613d5465973e1a0437bfc484f24cb90e01
